-   id: conda-export
    name: Conda export
    description: This hook compares your conda environment export to a saved version.
    entry: trurl conda-export
    language: python
    always_run: true
    pass_filenames: false