[tool.isort]
profile = "black"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
trurl = "trurl.cli:main"

[project]
name = "trurl"
version = "v0.0.0",
description = "Another python package for traceable and reproducible data science."
authors = [
  { name = "Jack Coggins", email = "jackhjfission@gmail.com" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dependencies = [
  "click==8.*",
]

[project.urls]
"Homepage" = "https://github.com/jackhjfission/trurl"
