services:
  trurl-dev:
    image:
      ${IMAGE_NAME}:${IMAGE_VERSION}
    ports:
      - 8888:8888
    volumes:
      - ../.:/home/jovyan/work
    environment:
      - CONTAINER_NAME=${IMAGE_NAME}:${IMAGE_VERSION}
      - TRURL_CONFIG_PATH=/home/jovyan/work/pyproject.toml