#!/opt/conda/bin/python

import os
import tomllib

if __name__ == "__main__":
    deps_path = os.path.join(os.path.dirname(__file__), "..", "pyproject.toml")
    pinned_path = os.path.join("/", "opt", "conda", "conda-meta", "pinned")

    with open(deps_path, "rb") as fp:
        deps = "\n" + "\n".join(tomllib.load(fp)["project"]["dependencies"]) + "\n"

    with open(pinned_path, "a") as fp:
        fp.write(deps)

    print(deps.replace("\n", " ")[1:-1])
